title: "My Personal Blog"
description: "Welcome to my personal blog."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # your base URL
author: "Your Name"
theme: minima

# Build settings
markdown: kramdown
